### **Randomly generate a directed acyclic graph (DAG) using the Erdos_Renyi model.**

In [4]:
from Random_Graph import ErdosRenyi

num_nodes = 10
average_degree = 3 # means that on average each node is connected to 5 other nodes
p_edge = 0.2 # means there is a 20% chance of an edge between any two nodes
generator = ErdosRenyi(
        num_nodes=num_nodes,  expected_degree=average_degree, def_topological_order = True   
        # num_nodes=num_nodes, p_edge=p_edge
        
    )

Adj_matrix = generator.get_random_graph()  # np.array of shape (num_nodes, num_nodes)

# Adj_matrix[i, j] = 1 means there is an edge from node i to node j

print(f"original graph:\n {Adj_matrix}")



original graph:
 [[0 0 1 1 1 0 0 0 0 0]
 [0 0 0 0 1 0 1 0 0 0]
 [0 0 0 0 0 0 1 0 0 1]
 [0 0 0 0 0 0 0 1 1 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 1 0 1]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


### **Calculate the average degree of the adjacency matrix.**

In [8]:
from networkx.algorithms.assortativity.connectivity import average_degree_connectivity
import networkx as nx
import numpy as np


# num = Adj_matrix.shape[0]
# G = nx.Graph()  
# G.add_nodes_from(range(num))
# for i in range(num):
#     for j in range(i + 1, num):
#         if Adj_matrix[i][j] != 0:
#             G.add_edge(i, j)

# Convert the adjacency matrix to a NetworkX graph
G = nx.from_numpy_array(Adj_matrix)

# Calculate the average degree of neighbors for each node
neighbor_avg_degree = nx.average_neighbor_degree(G)

# Print the average degree of neighbors for each node
print("Neighbor Average Degree (per node):", neighbor_avg_degree)

# Calculate the overall average degree of neighbors for the graph
overall_avg_neighbor_degree = np.mean(list(neighbor_avg_degree.values()))
print("Overall Average Neighbor Degree:", overall_avg_neighbor_degree)


Neighbor Average Degree (per node): {0: 3.0, 1: 3.5, 2: 3.3333333333333335, 3: 2.6666666666666665, 4: 3.0, 5: 3.25, 6: 2.75, 7: 3.3333333333333335, 8: 3.5, 9: 3.3333333333333335}
Overall Average Neighbor Degree: 3.166666666666667


### **Save the adjacency matrix**

In [5]:
import os
import pandas as pd
# Convert the adjacency matrix into a pandas DataFrame and assign indices to its rows and columns, labeled as V1, V2, V3, ..., Vn
Adj_matrix_df = pd.DataFrame(Adj_matrix, index=[f'V{i+1}' for i in range(num_nodes)], columns=[f'V{i+1}' for i in range(num_nodes)])

adjacency_matrix_path = os.path.join(r'data_bif', f'random_graph_{num_nodes}.csv')
Adj_matrix_df.to_csv(adjacency_matrix_path, index=True, header=True) # index=True indicates to save the index(line names), header=True indicates to save the column names

# read the CSV file and print the DataFrame
load_path = os.path.join(r'data_bif', f'random_graph_{num_nodes}.csv')
df = pd.read_csv(load_path, index_col=0)  # index_col=0 indicates the first column is the index
# print(df)

### **Convert an adjacency matrix without topological sorting into one with topological sorting**

In [ ]:
import numpy as np
import networkx as nx

# Randomly shuffle the rows
shuffled_rows = np.random.permutation(Adj_matrix_df.index)
Adj_matrix_df = Adj_matrix_df.loc[shuffled_rows]

# Randomly shuffle the columns
shuffled_cols = np.random.permutation(Adj_matrix_df.columns)
Adj_matrix_df = Adj_matrix_df[shuffled_cols]

print(Adj_matrix_df)

node_list = Adj_matrix_df.index.tolist()  # get the node list from the index of the DataFrame
# create the nx.DiGraph object base on the above DAG adjacency matrix and node list
DAG = nx.DiGraph()
DAG.add_nodes_from(node_list)  
for source in node_list:
    for target in node_list:
        if Adj_matrix_df.loc[source, target] == True:
            DAG.add_edge(source, target)

# get the topological order of the DAG
topological_order = list(nx.topological_sort(DAG))
print(f'topological_order:{topological_order}')


# rearrange the adjacency matrix according to the topological order
order_adjacency_matrix = Adj_matrix_df.loc[topological_order, topological_order]
print(f"order_adjacency_matrix:\n {order_adjacency_matrix},\n type(order_adjacency_matrix):{type(order_adjacency_matrix)}")

     V2  V1  V8  V7  V5  V4  V9  V6  V10  V3
V4    0   0   1   0   0   0   1   0    0   0
V1    0   0   0   0   1   1   0   0    0   1
V5    0   0   0   0   0   0   0   1    0   0
V2    0   0   0   1   1   0   0   0    0   0
V9    0   0   0   0   0   0   0   0    0   0
V8    0   0   0   0   0   0   0   0    1   0
V10   0   0   0   0   0   0   0   0    0   0
V3    0   0   0   1   0   0   0   0    1   0
V7    0   0   0   0   0   0   1   0    0   0
V6    0   0   1   1   0   0   0   0    1   0
topological_order:['V1', 'V2', 'V4', 'V3', 'V5', 'V6', 'V8', 'V7', 'V10', 'V9']
order_adjacency_matrix:
      V1  V2  V4  V3  V5  V6  V8  V7  V10  V9
V1    0   0   1   1   1   0   0   0    0   0
V2    0   0   0   0   1   0   0   1    0   0
V4    0   0   0   0   0   0   1   0    0   1
V3    0   0   0   0   0   0   0   1    1   0
V5    0   0   0   0   0   1   0   0    0   0
V6    0   0   0   0   0   0   1   1    1   0
V8    0   0   0   0   0   0   0   0    1   0
V7    0   0   0   0   0   0   0   0    0