**Randomly generate a directed acyclic graph (DAG) using the Erdos_Renyi model.**

In [ ]:
from Random_Graph import ErdosRenyi

num_nodes = 20
average_degree = 5 # means that on average each node is connected to 5 other nodes
p_edge = 0.2 # means there is a 20% chance of an edge between any two nodes
generator = ErdosRenyi(
        # num_nodes=num_nodes,  expected_degree=average_degree     
        num_nodes=num_nodes, p_edge=p_edge
    )

Adj_matrix = generator.get_random_graph()  # np.array of shape (num_nodes, num_nodes)

# Adj_matrix[i, j] = 1 means there is an edge from node i to node j

print(f"original graph:\n {Adj_matrix}")



original graph:
 [[0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 1 1 0 1 1]
 [0 0 1 0 0 0 0 1 0 1 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1]
 [0 0 0 0 0 0 1 1 0 0 0 0 0 1 1 1 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 1 0 0 1 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]


**Calculate the average degree of the adjacency matrix.**

In [ ]:
from networkx.algorithms.assortativity.connectivity import average_degree_connectivity
import networkx as nx
import numpy as np


# num = Adj_matrix.shape[0]
# G = nx.Graph()  
# G.add_nodes_from(range(num))
# for i in range(num):
#     for j in range(i + 1, num):
#         if Adj_matrix[i][j] != 0:
#             G.add_edge(i, j)

# Convert the adjacency matrix to a NetworkX graph
G = nx.from_numpy_array(Adj_matrix)

# Calculate the average degree of neighbors for each node
neighbor_avg_degree = nx.average_neighbor_degree(G)

# Print the average degree of neighbors for each node
print("Neighbor Average Degree (per node):", neighbor_avg_degree)

# Calculate the overall average degree of neighbors for the graph
overall_avg_neighbor_degree = np.mean(list(neighbor_avg_degree.values()))
print("Overall Average Neighbor Degree:", overall_avg_neighbor_degree)


Neighbor Average Degree (per node): {0: 4.666666666666667, 1: 3.75, 2: 4.666666666666667, 3: 5.5, 4: 3.4, 5: 4.5, 6: 4.0, 7: 4.0, 8: 4.75, 9: 4.25, 10: 4.0, 11: 4.25, 12: 6.0, 13: 4.0, 14: 4.333333333333333, 15: 4.6, 16: 4.166666666666667, 17: 5.0, 18: 4.4, 19: 3.6666666666666665}
Overall Average Neighbor Degree: 4.3950000000000005


**Save the adjacency matrix**

In [ ]:
import os
import pandas as pd
# 将邻接矩阵转换成pd的格式，并且给它的列和行都加上索引，索引为V1, V2, V3, ..., Vn
Adj_matrix_df = pd.DataFrame(Adj_matrix, index=[f'V{i+1}' for i in range(num_nodes)], columns=[f'V{i+1}' for i in range(num_nodes)])

adjacency_matrix_path = os.path.join(r'data_bif', f'random_graph_{num_nodes}.csv')
Adj_matrix_df.to_csv(adjacency_matrix_path, index=True, header=True) # index=True indicates to save the index(line names), header=True indicates to save the column names

# read the CSV file and print the DataFrame
load_path = os.path.join(r'data_bif', f'random_graph_{num_nodes}.csv')
df = pd.read_csv(load_path, index_col=0)  # index_col=0 indicates the first column is the index
# print(df)